version: "3"

services:
    hivegame:
        build:
            context: ./hive_game
        ports:
            - "8080:80"
        depends_on:
            - database
        command: php -S 0.0.0.0:80 -t src/
        networks:
            - network

    database:
        build:
            context: ./database
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=hive
            - MYSQL_USER=hiveuser
            - MYSQL_PASSWORD=hivepassword
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - network

    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "8081:8080"
            - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home

    sonarqube:
        image: sonarqube:latest
        ports:
            - "9000:9000"
        volumes:
            - sonarqube-data:/opt/sonarqube/data

volumes:
    jenkins-data:
    sonarqube-data:
    db-data:

networks:
    network:
